src/main/java/cz/upce/fei/nnptp/zz/controller/main.java
src/main/java/cz/upce/fei/nnptp/zz/controller/package-info.java
src/main/java/cz/upce/fei/nnptp/zz/entity/CryptoFile.java
src/main/java/cz/upce/fei/nnptp/zz/entity/JSON.java
src/main/java/cz/upce/fei/nnptp/zz/entity/Parameter.java
src/main/java/cz/upce/fei/nnptp/zz/entity/ParameterTye.java
src/main/java/cz/upce/fei/nnptp/zz/entity/Password.java
src/main/java/cz/upce/fei/nnptp/zz/entity/PasswordDatabase.java
src/main/java/cz/upce/fei/nnptp/zz/entity/package-info.java
src/test/java/cz/upce/fei/nnptp/zz/entity/CryptoFileTest.java
src/test/java/cz/upce/fei/nnptp/zz/entity/PasswordTest.java

Fixed packages paths

---

src/main/java/cz/upce/fei/nnptp/zz/entity/ParameterTye.java

Updated Enum Fields according to naming convention

---

src/main/java/cz/upce/fei/nnptp/zz/controller/Main.java
src/main/java/cz/upce/fei/nnptp/zz/entity/ParameterType.java

Fixed class names

---

src/main/java/cz/upce/fei/nnptp/zz/entity/PasswordDatabase.java

Renamed some variables and parameters in class PasswordDatabase to better reflect their purpose. st52557

Renamed some variables and parameters

---

src/main/java/cz/upce/fei/nnptp/zz/entity/CryptoFile.java

Fixed catch cases by collapsing

---

src/test/java/cz/upce/fei/nnptp/zz/entity/PasswordDatabaseTest.java

password database save&load passwords test

---

src/test/java/cz/upce/fei/nnptp/zz/entity/PasswordTest.java

Refactoring test method in PasswordTest

---

src/main/java/cz/upce/fei/nnptp/zz/entity/Password.java

Refactored class Password - get rid of comment and useless constructor.

---

src/main/java/cz/upce/fei/nnptp/zz/entity/JSON.java
src/main/java/cz/upce/fei/nnptp/zz/entity/Parameter.java
src/main/java/cz/upce/fei/nnptp/zz/entity/Password.java
src/test/java/cz/upce/fei/nnptp/zz/entity/JSONTest.java

- Static constructor for Parameter types.
- Password toString method for json testing.
- Implementation of fromJson function.
- Test for implemented function.

From json implementation

---

src/main/java/cz/upce/fei/nnptp/zz/entity/CryptoFile.java

Try-catch changed on try-with-resources.

---

src/main/java/cz/upce/fei/nnptp/zz/entity/Parameter.java
src/main/java/cz/upce/fei/nnptp/zz/entity/Password.java

Refactored switch to get rid of duplicated code.

---

src/main/java/cz/upce/fei/nnptp/zz/entity/Password.java

Parameters HashMap initialized in Password constructor.

---

src/main/java/cz/upce/fei/nnptp/zz/entity/PasswordDatabase.java

Contributed by Ondřej Matějka (st61019)

Fixed condition in findEntryByTitle method

---

README.md
src/main/java/cz/upce/fei/nnptp/zz/entity/JSON.java
src/main/java/cz/upce/fei/nnptp/zz/entity/Parameter.java
src/main/java/cz/upce/fei/nnptp/zz/entity/Password.java
src/test/java/cz/upce/fei/nnptp/zz/entity/JSONTest.java

Contributed by Ondřej Matějka (st61019)

toJson implemenation with test

---

src/main/java/cz/upce/fei/nnptp/zz/entity/CryptoFile.java
src/test/java/cz/upce/fei/nnptp/zz/entity/CryptoFileTest.java

- Implemented AES encryption for CryptoFile
- Added respective test to CryptoFile class

Implementation of AES encryption for CryptoFile

---

src/main/java/cz/upce/fei/nnptp/zz/entity/CryptoFile.java

Replaced strings with symbolic constants, to better reflect their purpose for future reader/coder. st52557

Replaced strings with symbolic constants.

---

src/main/java/cz/upce/fei/nnptp/controller/Main.java
src/main/java/cz/upce/fei/nnptp/controller/package-info.java
src/main/java/cz/upce/fei/nnptp/entity/CryptoFile.java
src/main/java/cz/upce/fei/nnptp/entity/JSON.java
src/main/java/cz/upce/fei/nnptp/entity/Parameter.java
src/main/java/cz/upce/fei/nnptp/entity/ParameterType.java
src/main/java/cz/upce/fei/nnptp/entity/Password.java
src/main/java/cz/upce/fei/nnptp/entity/PasswordDatabase.java
src/main/java/cz/upce/fei/nnptp/entity/package-info.java
src/test/java/cz/upce/fei/nnptp/entity/CryptoFileTest.java
src/test/java/cz/upce/fei/nnptp/entity/JSONTest.java
src/test/java/cz/upce/fei/nnptp/entity/PasswordDatabaseTest.java
src/test/java/cz/upce/fei/nnptp/entity/PasswordTest.java

Resolved merge conflicts from pull request #30.

Removed unnecessary .zz. package space.

---

src/main/java/cz/upce/fei/nnptp/zz/entity/Password.java

Password toString method fixed to work with non-standardized parameters

---

src/main/java/cz/upce/fei/nnptp/entity/Password.java

Refactoring hasParameter and getParamater. Tomáš Slabý (st55434)

Refactoring hasParameter and getParamater

---

src/main/java/cz/upce/fei/nnptp/zz/controller/Main.java
src/main/java/cz/upce/fei/nnptp/zz/entity/CryptoFile.java
src/main/java/cz/upce/fei/nnptp/zz/entity/JSON.java
src/main/java/cz/upce/fei/nnptp/zz/entity/Parameter.java
src/main/java/cz/upce/fei/nnptp/zz/entity/ParameterType.java
src/main/java/cz/upce/fei/nnptp/zz/entity/Password.java
src/main/java/cz/upce/fei/nnptp/zz/entity/PasswordDatabase.java

Added javadoc comments to the project, this time sticking to one change per pull request as mentioned before.
st69801

Adding JavaDoc comments

---

pom.xml
src/main/java/cz/upce/fei/nnptp/entity/JSON.java
src/main/java/cz/upce/fei/nnptp/entity/PasswordDatabase.java

First commit - implemented methods save load only for running test purpouse. Refactored method fromJson().
Second commit - methods toJson() extended for working with multiple data. TestFromJson() passed!

Refactored and extended method fromJson().

---

src/main/java/cz/upce/fei/nnptp/entity/CryptoFile.java

Add constants

---

src/main/java/cz/upce/fei/nnptp/entity/CryptoFile.java
src/main/java/cz/upce/fei/nnptp/entity/JSON.java
src/main/java/cz/upce/fei/nnptp/entity/Parameter.java
src/main/java/cz/upce/fei/nnptp/entity/PasswordGenerator.java
src/main/java/cz/upce/fei/nnptp/validation/Validator.java
src/test/java/cz/upce/fei/nnptp/entity/PasswordParameterTest.java
src/test/java/cz/upce/fei/nnptp/entity/PasswordTest.java

Implementing support for adding more validation rules for parameters.

Validation rules

---

src/main/java/cz/upce/fei/nnptp/entity/PasswordGenerator.java

Fixing variable names so they follow the Oracle code conventions.

---

src/main/java/cz/upce/fei/nnptp/entity/PasswordGenerator.java
src/test/java/cz/upce/fei/nnptp/entity/PasswordGeneratorTest.java

Refactoring PasswordGenerator
